### ISSUE TITLE
Communicator 

### ISSUE THREAD

**Issue by nick-benoit14** [SmallSatGasTeam/errno#16]
I think that we will need to abstract the idea of radio communication out of the main program. I think we should use linux sockets to transfer data to another program that will wrap our main program. This will enable us to be able to upload a new main program if need be. 

Linux socket info http://www.linuxhowtos.org/C_C++/socket.htm

**Comment by sjkelleyjr** [comment]
this is similar to how SDL does things in the embedded systems
